import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/Header"
import Hero from "@/app/components/Hero"
import Introduction from "@/app/components/Introduction";
import Skills from "@/app/components/Skills"
import Projects from "@/app/components/Projects"
import Footer from "@/app/components/Footer"
import "bootstrap-icons/font/bootstrap-icons.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
          <Header/>
          {/* <Hero/> */}
          {/* <Introduction/> */}
          {/* <Skills/> */}
          {/* <Projects/> */}          
        {children}
        <Footer/>
      </body>
    </html>
  );
}
